### ISSUE TITLE
tesscube is 100x slower than tessrip on TIKE

### ISSUE THREAD

**Issue by mrtommyb** [tessgi/tesscube#9]
I ran this same code on the current version on tesscube and at 334a92e514368d96f090b6703bc128dabc433640. 

```python
r = Rip(sector=31, camera=3, ccd=4) # substituting Rip for TESSCube in the new version
c = (242, 109)
tpf = r.get_tpf(c, shape=(15, 15))
```
I get 4.02 s ± 18.6 ms per loop on tesscube and 47.8 ms ± 1.39 ms per loop on tessrip.

**Comment by christinahedges** [comment]
Hi @mrtommyb thanks for opening this issue, this is indeed an unacceptable slow down. I have just put in an update to address this.

There were two reasons for this slow down, one was an oversight where I was unnecessarily recalculating the fits headers for each TPF, instead of at the cube level. Now the cube takes longer to initialize (~1 second), but the TPFs will generate faster. 

The second was that calculating the POS_CORR columns was taking time. Unfortunately, if you want POS_CORR, it will take a little time to calculate. 

The rest of the slow down is largely 1) building extra fits components to make the data look like SPOC data and 2) applying the correct WCS.

Since I don't think you need it, I've made a `calculate_poscorr` keyword in `get_tpf`. If you want the fastest generation possible, you can turn that off and it will be zero by default. 

```python
c = (242, 109)
tpf = r.get_tpf(c, shape=(15, 15), calculate_poscorr=False)
```
Result: 198 ms ± 4.97 ms

```python
c = (242, 109)
tpf = r.get_tpf(c, shape=(15, 15))
```
Result: 1.83 s ± 156 ms

This is available in v1.0.1dev, please go ahead and give it a try.
